---
- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - build-sphinx-docs
        - dco-license
        - yamllint
    gate:
      jobs:
        - ansible-lint
        - build-sphinx-docs
        - dco-license
        - yamllint
    post:
      jobs:
        - osism-publish-tox-docs-production
