---
- name: Add groups
  become: true
  ansible.builtin.group:
    name: "{{ item['name'] }}"
    state: present
  with_items:
    - "{{ user_list }}"

- name: Add users
  become: true
  ansible.builtin.user:
    name: "{{ item['name'] }}"
    createhome: true
    shell: /usr/bin/bash
    group: "{{ item['name'] }}"
    state: present
  with_items:
    - "{{ user_list }}"

- name: Copy SSH-Key
  become: true
  ansible.posix.authorized_key:
    user: "{{ item['name'] }}"
    key: "{{ item['key'] }}"
  with_items:
    - "{{ user_list }}"

- name: Install sudo package
  become: true
  ansible.builtin.package:
    name: sudo
    state: present

- name: Create sudoers files
  become: true
  ansible.builtin.template:
    src: config.j2
    dest: "/etc/sudoers.d/{{ item['name'] }}"
    owner: root
    group: root
    mode: 0440
  with_items:
    - "{{ user_list }}"

- name: Remove sudoers files
  become: true
  ansible.builtin.file:
    dest: "/etc/sudoers.d/{{ item }}"
    state: absent
  with_items:
    - "{{ user_delete }}"

- name: Remove users
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    remove: true
    state: absent
  with_items:
    - "{{ user_delete }}"

- name: Remove groups
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ user_delete }}"
